version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - '/home/homer/.openvpn/:/etc/openvpn/custom'
            - '/home/homer/.transmission/:/config'
            - '/mnt/data/homer/files/Transmission/:/data'
            - '/var/local/transmission:/var/local/transmission'
            - '/run/transmission.sock:/run/transmission.sock'
        environment:
            - OPENVPN_PROVIDER=PRIVATEVPN
            - OPENVPN_CONFIG=IE Dublin
            - OPENVPN_USERNAME=ant.soulier@gmail.com
            - OPENVPN_PASSWORD=Fju4Luh9YvVBea-
            - LOCAL_NETWORK=192.168.68.0/22
            - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
            - TRANSMISSION_RPC_USERNAME=homer
            - TRANSMISSION_RPC_PASSWORD=bee1JoozaiY6ni6a
            - TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=true
            - TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME="/var/local/transmission/done"
            - TRANSMISSION_INCOMPLETE_DIR="/data"
            - TRANSMISSION_DOWNLOAD_DIR="/data"
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn


# For external access, and HTTPS, add the following rules in nginx configuration:
#
# server {
#     ...
#     location ~ /transmission {
#         proxy_pass http://127.0.0.1:9091;
#     }
#     ...
# }
